### ISSUE TITLE
Need git show for single file.

### ISSUE THREAD

**Issue by twcrone** [schacon/ruby-git#164]
I've added this hack to my project to return the text of a single file at a given SHA.  I didn't see an easy way to do it without directing sending a message to Lib.command.  I'd like to use something existing in ruby-git or make a PR for this feature.  What do you think?

```
    def revision sha_ref
      # just until we can get a proper git.show(sha, path) pulled into Git gem.
      @git.lib.send(:command, 'show', ["#{sha_ref}:#{file_path}"])
    end
```

**Comment by robertodecurnex** [comment]
```ruby
Git.open('.').show('object_reference', 'file/path')
```

Will make the trick.
