### ISSUE TITLE
Dead repository?

### ISSUE THREAD

**Issue by flbulgarelli** [schacon/ruby-git#268]
Hi @schacon !

Nice gem, I am currently using it in some projects.  

However, this repository seems to be quite dead for a year or so - no commits, no PRs merged :cry: . Is someone maintaining it?

Thanks!

**Comment by spacemoose** [comment]
It would be nice if the following information were on the front page of the repo, but it seems that this and the follow-up gem have been deprecated.    See the discussion here: 

http://programmers.stackexchange.com/questions/62843/best-ruby-git-library

It would seem that the current go-to library for git access within ruby is called Rugged, a wrapper around a c api called lib2git.

http://programmers.stackexchange.com/questions/62843/best-ruby-git-library

**Comment by flbulgarelli** [comment]
Thanks @spacemoose
