### ISSUE TITLE
How clone a private repo ?

### ISSUE THREAD

**Issue by RedaBenh** [schacon/ruby-git#309]
I need to clone a repo a private github repo ? 
I check the code and the option , no way to define a username/password of ssh key.
How can i do it with this gem ?

Thanks for your help

**Comment by ankitchachada** [comment]
@RedaBenh did you find a way to do that?

**Comment by lucywyman** [comment]
I think this mostly depends on the URI you use to clone the repo. I was able to use `git@github.com:my_user/repo.git` without putting in a password. It also looks like `https://username:password@github.com/username/repository.git`, but I can't say for sure if that works or not. 

Let me know if that doesn't work for your use case!

**Comment by RedaBenh** [comment]
I finally use this format: 
`git clone https://<token>:x-oauth-basic@github.com/owner/repo.git`

See https://github.com/blog/1270-easier-builds-and-deployments-using-git-over-https-and-oauth

Regards
